os: windows

language: shell

python: "3.8"

before_install:
    - choco install python --version=3.8.0 
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - pip install pipenv
    - python -m venv .venv

install:
  - pipenv install --dev

script:
  - pipenv run pytest --cov=odk_servermanager tests

after_success:
  - pipenv run coveralls
