name: Ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:

  ci:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          pipenv install --dev

      - name: Update PYTHONPATH to enable imports in tests
        run: echo "PYTHONPATH=D:/a/odk_servermanager/odk_servermanager" >> $GITHUB_ENV
        shell: bash

      - name: Run tests
        run: |
          pipenv run pytest --cov=odk_servermanager tests
        shell: cmd

      - name: Prepare the coveralls config.
        run: echo "COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }}" >> $GITHUB_ENV
        shell: bash

      - name: Upload coverage
        run: |
          pipenv run coveralls
