name: Ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:

  ci:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pipenv'

      - name: updating PATH to enable importing my package
        run: echo "PYTHONPATH=D:/a/odk_servermanager/odk_servermanager" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          pip install pipenv
          python -m venv .venv
          pipenv install --dev

      - name: Run tests
        run: |
          echo %PYTHONPATH%
          pipenv run pytest --cov=odk_servermanager tests
        shell: cmd

      - name: Coveralls
        uses: coverallsapp/github-action@v2